[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:mariadb]
command=/usr/bin/mariadbd
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/mysql.log
stderr_logfile=/var/log/supervisor/mysql-error.log
priority=1

[program:finvue]
command=/usr/bin/python3 main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/finvue.log
stderr_logfile=/var/log/supervisor/finvue-error.log
priority=10
startsecs=15