-- 运营数据看板表结构

-- 直播数据表 (对应线下 douyin_creator_live_overview)
CREATE TABLE IF NOT EXISTS finvue_operation_live_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account VARCHAR(255) NOT NULL COMMENT '账号名称',
  room_id VARCHAR(191) NOT NULL COMMENT '直播ID',
  title VARCHAR(512) COMMENT '直播标题',
  start_time DATETIME COMMENT '开播时间',
  end_time DATETIME COMMENT '关播时间',
  duration INT DEFAULT 0 COMMENT '直播时长(分钟)',
  pcu INT DEFAULT 0 COMMENT '峰值人数',
  acu INT DEFAULT 0 COMMENT '平均人数',
  earn_score INT DEFAULT 0 COMMENT '收获音浪',
  fans_earn_score INT DEFAULT 0 COMMENT '粉丝音浪',
  non_fans_earn_score INT DEFAULT 0 COMMENT '非粉音浪',
  first_earn_score VARCHAR(64) COMMENT '首次送礼用户音浪',
  consume_ucnt INT DEFAULT 0 COMMENT '送礼人数',
  fans_consume_ucnt INT DEFAULT 0 COMMENT '送礼粉丝人数',
  non_fans_consume_ucnt INT DEFAULT 0 COMMENT '送礼非粉人数',
  first_consume_ucnt VARCHAR(64) COMMENT '首次送礼人数',
  expected_total_income FLOAT DEFAULT 0 COMMENT '预计收入',
  show_ucnt INT DEFAULT 0 COMMENT '曝光人数',
  watch_ucnt INT DEFAULT 0 COMMENT '观看人数',
  fans_watch_ucnt INT DEFAULT 0 COMMENT '观看粉丝人数',
  non_fans_watch_ucnt INT DEFAULT 0 COMMENT '观看非粉人数',
  follow_ucnt INT DEFAULT 0 COMMENT '涨粉人数',
  unfollow_ucnt INT DEFAULT 0 COMMENT '掉粉人数',
  join_fansclub_ucnt INT DEFAULT 0 COMMENT '加团人数',
  avg_watch_duration FLOAT DEFAULT 0 COMMENT '人均停留时长(分钟)',
  fans_avg_watch_duration FLOAT DEFAULT 0 COMMENT '粉丝人均停留时长(分钟)',
  non_fans_avg_watch_duration FLOAT DEFAULT 0 COMMENT '非粉人均停留时长(分钟)',
  comment_ucnt INT DEFAULT 0 COMMENT '评论人数',
  fans_comment_ucnt INT DEFAULT 0 COMMENT '评论粉丝人数',
  non_fans_comment_ucnt INT DEFAULT 0 COMMENT '评论非粉人数',
  like_cnt INT DEFAULT 0 COMMENT '点赞次数',
  fans_like_cnt INT DEFAULT 0 COMMENT '点赞粉丝次数',
  non_fans_like_cnt INT DEFAULT 0 COMMENT '点赞非粉次数',
  share_cnt INT DEFAULT 0 COMMENT '分享次数',
  fans_share_cnt INT DEFAULT 0 COMMENT '分享粉丝次数',
  non_fans_share_cnt INT DEFAULT 0 COMMENT '分享非粉次数',
  show_cnt_dist VARCHAR(512) COMMENT '曝光分布',
  watch_ucnt_dist VARCHAR(512) COMMENT '观看分布',
  fans_in_group FLOAT DEFAULT 0 COMMENT '群内粉丝',
  fans_out_group FLOAT DEFAULT 0 COMMENT '群外粉丝',
  watch_u_rate FLOAT DEFAULT 0 COMMENT '观看率',
  follow_u_rate FLOAT DEFAULT 0 COMMENT '涨粉率',
  comment_u_rate FLOAT DEFAULT 0 COMMENT '评论率',
  consume_u_rate FLOAT DEFAULT 0 COMMENT '送礼率',
  fans_watch_u_rate FLOAT DEFAULT 0 COMMENT '粉丝观看率',
  fans_comment_u_rate FLOAT DEFAULT 0 COMMENT '粉丝评论率',
  fans_like_rate FLOAT DEFAULT 0 COMMENT '粉丝点赞率',
  fans_share_rate FLOAT DEFAULT 0 COMMENT '粉丝分享率',
  fans_consume_u_rate FLOAT DEFAULT 0 COMMENT '粉丝送礼率',
  fans_in_group_rate FLOAT DEFAULT 0 COMMENT '群内粉丝率',
  created_at DATETIME COMMENT '数据创建时间',
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  UNIQUE KEY uk_finvue_operation_live_stats_room (room_id),
  INDEX idx_finvue_operation_live_stats_account_time (account, start_time),
  INDEX idx_finvue_operation_live_stats_time (start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='直播数据统计';

-- 短视频数据表
CREATE TABLE IF NOT EXISTS finvue_operation_video_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account VARCHAR(255) NOT NULL COMMENT '账号名称',
  video_id VARCHAR(191) COMMENT '视频ID',
  title VARCHAR(512) COMMENT '作品名称',
  publish_time DATETIME COMMENT '发布时间',
  duration_type VARCHAR(32) COMMENT '体裁(1min-/1-3min/3-5min/5min+)',
  play_count INT DEFAULT 0 COMMENT '播放量',
  like_count INT DEFAULT 0 COMMENT '点赞数',
  comment_count INT DEFAULT 0 COMMENT '评论数',
  share_count INT DEFAULT 0 COMMENT '分享数',
  completion_rate FLOAT DEFAULT 0 COMMENT '完播率',
  5s_completion_rate FLOAT DEFAULT 0 COMMENT '5秒完播率',
  2s_exit_rate FLOAT DEFAULT 0 COMMENT '2秒跳出率',
  interaction_rate FLOAT DEFAULT 0 COMMENT '互动率',
  follow_count INT DEFAULT 0 COMMENT '涨粉数',
  created_at DATETIME COMMENT '数据创建时间',
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  UNIQUE KEY uk_finvue_operation_video_stats_account_time (account, publish_time, title(100)),
  INDEX idx_finvue_operation_video_stats_account_time (account, publish_time),
  INDEX idx_finvue_operation_video_stats_time (publish_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='短视频数据统计';

-- TOP200粉丝数据表 (可选，用于粉丝趋势分析)
CREATE TABLE IF NOT EXISTS finvue_operation_fans_stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  account VARCHAR(255) NOT NULL COMMENT '账号名称',
  anchor_name VARCHAR(255) NOT NULL COMMENT '主播名称',
  stat_date DATE NOT NULL COMMENT '统计日期',
  total_core_fans INT DEFAULT 0 COMMENT '核心粉丝总量(>=4场)',
  active_core_fans INT DEFAULT 0 COMMENT '核心追随粉(近30天活跃)',
  churned_core_fans INT DEFAULT 0 COMMENT '核心流失粉',
  new_active_fans INT DEFAULT 0 COMMENT '新晋活跃粉',
  dead_fans INT DEFAULT 0 COMMENT '死忠粉(>=20场)',
  high_freq_fans INT DEFAULT 0 COMMENT '高频粉(10-19场)',
  mid_freq_fans INT DEFAULT 0 COMMENT '中频粉(4-9场)',
  low_freq_fans INT DEFAULT 0 COMMENT '偶发粉(1-3场)',
  live_count INT DEFAULT 0 COMMENT '直播场次',
  unique_viewers INT DEFAULT 0 COMMENT '去重观看人数',
  cohort_data JSON COMMENT '同期群数据',
  raw JSON COMMENT '原始数据',
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  UNIQUE KEY uk_finvue_operation_fans_stats_anchor_date (anchor_name, stat_date),
  INDEX idx_finvue_operation_fans_stats_anchor_time (anchor_name, stat_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='TOP200粉丝统计';

-- 导入记录表 (用于追踪导入历史)
CREATE TABLE IF NOT EXISTS finvue_operation_import_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  import_type VARCHAR(32) NOT NULL COMMENT '导入类型(live/video/fans)',
  file_name VARCHAR(512) NOT NULL COMMENT '文件名',
  record_count INT DEFAULT 0 COMMENT '导入记录数',
  account_count INT DEFAULT 0 COMMENT '账号数量',
  status VARCHAR(32) NOT NULL DEFAULT 'success' COMMENT '状态(success/failed/partial)',
  error_message TEXT COMMENT '错误信息',
  imported_by VARCHAR(191) COMMENT '导入人',
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  INDEX idx_finvue_operation_import_logs_type_time (import_type, imported_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据导入日志';